version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CREATE_TOPICS: send-message:1:1

  mongo:
    image: mongo
    container_name: chatty-mongo
    ports:
      - 28017:27017
    environment:
      MONGO_INITDB_DATABASE: chatty    
    volumes: 
      - ~/mongo/data:/data/db

  core-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: nodejs
    depends_on:
      - mongo
    container_name: chatty-core
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    volumes: 
      - .:/home/chatty/app
    command: node ./src/index.js
    environment:
      MONGO_URI: mongodb://mongo:27017/chatty
